name: Mark Gbur
favicon: null
layout_spectrum: 0.10959982732310891
typography_spectrum: 0.7677731767762452
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.33152668131515384
  lightness: 0.9410894506145269
  saturation: 0.5535408523865044
  rhythmicContrast: 0.8764779067132622
purpose: []
